import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/context/ThemeProvider';
import NextTopLoader from 'nextjs-toploader';
import ToastProvider from '@/context/ToastProvider';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <ToastProvider>
            <NextTopLoader color={'#2663E9'} />
            {children}
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
